export const useracc = [
  {
    name: "Ivan Panov",
    email: "admin@admin.com",
    password: "12345",
  },
  {
    name: "Ivan Panov 1",
    email: "ivan.panov@yahoo.com",
    password: "56789",
  },
  {
    name: "Ivan Panov 2",
    email: "nekoj@admin.com",
    password: "asdfg",
  },
];

export const categoriesItems = [
  {
    id: 1,
    type: "snowboards",
    img: "img/snowboards/product-1.png",
    text: "Snowboards",
  },
  {
    id: 2,
    type: "bindings",
    img: "img/SnowboardBindings/product-1.png",
    text: "Bindings",
  },
  {
    id: 3,
    type: "boots",
    img: "img/snowboardsboots/product-1.png",
    text: "Snowboard Boots",
  },
  {
    id: 4,
    type: "jacket",
    img: "img/jacket/product-1.png",
    text: "Jacket",
  },
  {
    id: 5,
    type: "pants",
    img: "img/pants/product-1.png",
    text: "Pants",
  },
  {
    id: 6,
    type: "helmet",
    img: "img/helmet/product-1.png",
    text: "Helmet",
  },

  {
    id: 7,
    type: "goggles",
    img: "img/goggles/product-1.png",
    text: "Goggles",
  },
];

export const items = [
  {
    id: 1,
    brand: "Burton",
    title: "Instigator Snowboard 2021",
    img: "img/snowboards/product-1.png",
    price: 200,
    gender: "men's",
    size: "154cm , 164cm",
    info:
      "Based on the award-winning Jibsaw board, the Rossignol Jibfluence Snowboard brings the same high-octane freestyle energy to lighter riders. At the center of the Jibfluence concept is a multi-radius sidecut and 3S serrated edges, which give the board precision control on the hardpack. Pair that with a nice soft flex pattern for a playful, easygoing feel, and the result is a board that's fun and powerful for youngsters looking to get tricky.",
    inCart: false,
    count: 0,
    total: 0,
    type: "snowboards",
  },
  {
    id: 2,
    brand: "Burton",
    title: "Day Trader Snowboard - Women's 2021",
    img: "img/snowboards/product-3.png",
    price: 220,
    gender: "women's",
    size: ["134cm"],
    info:
      "The economy, right? Can't live with it, can't live without it. All those numbers going up and down just gets you stoked out of your mind to start the new day. No? It's okay, us neither. If your idea of speculation involves wondering how sick its going to be next season, and you think IPO maybe stands for Initial Powder-day Opening, allow us to introduce you to your new broker. The Burton Day Trader Snowboard might not know a blue chip stock from a blue corn Tostito, but lay it over in some fluffy stuff and you'll see it's all about business. This smooth turning freeride stick floats higher than a bull market, and turns quicker than a short sale on the hardpack.",
    inCart: false,
    count: 0,
    total: 0,
    type: "c",
  },
  {
    id: 3,
    brand: "Burton",
    title: "Hover Cover Snowboard Cover - Big Kids' 2021",
    img: "img/snowboards/product-4.png",
    price: 220,
    gender: "kids",
    size: ["110cm"],
    info:
      "In the summer time when the weather is fine, you don't have to stop shredding. Get you kiddo to shred the kitchen with the Burton Hover Cover Snowboard Cover. Made of a felt based material that glides over any hard surface, the Hover Cover fits on any snowboard that is 90 cm or smaller. The best part about the Burton Hover Cover is that you can teach your grom how to snowboard, and clean the floors simultaneously.",
    inCart: false,
    count: 0,
    total: 0,
    type: "snowboards",
  },
  {
    id: 4,
    brand: "DC",
    title: "Powder Killer Snowboard 2021",
    img: "img/snowboards/product-2.png",
    price: 210,
    gender: "men's",
    size: ["145cm, 155cm"],
    info:
      "The snowboard formerly known as the HR is back and ready to mercilessly shred snow. Introducing the DC Powder Killer Snowboard with S-Camber and DC s Light Core, which brings powder hounds maximum float in deep snow. With this lively board, you're less likely to get caught in the deep dead zones when your speed hits doldrums. In fact, the DC Powder Killer Snowboard doesn't even know what a dead zone is. Why? Because it turns the most mundane terrain into a playground. If you're looking to play in powder with a smile on your face, the Powder Killer is at your service.",
    inCart: false,
    count: 0,
    total: 0,
    type: "snowboards",
  },
  {
    id: 5,
    brand: "CAPiTA",
    title: "Paradise Snowboard - Women's 2021",
    img: "img/snowboards/product-5.png",
    price: 250,
    gender: "women's",
    size: ["130cm , 145cm , 150cm"],
    info:
      "Some people think paradise is a tropical beach with white sands, warm water, and colorful drinks with little umbrellas in them. We believe that everyone's opinion is valid and deserves respect, and also that those people are wrong. We know for a fact that paradise is that last big storm of the year, when every line is filled in and covered with a fresh fluffy blanket, your legs are in prime shredding shape from a season of riding, the sun is out and shining, and you get to spend the whole day at your favorite resort with your best friends. The CAPiTA Paradise Snowboard is built with that exact idea in mind. It's got generous rocker in the tip and tail to float through the pow and blast through the chop, a smooth medium flex to lay some some sweet turns, and a true twin shape to show off a little bit on some end of the day park laps. Everything goes, all the landings are spotless. Welcome to paradise.",
    inCart: false,
    count: 0,
    total: 0,
    type: "snowboards",
  },
  {
    id: 6,
    brand: "Salomon",
    title: "Trigger X Snowboard Bindings 2021",
    img: "img/SnowboardBindings/product-1.png",
    price: 120,
    gender: "men's",
    size: ["S , M , L"],
    info:
      "Sight in your target line and attack with the Salomon Trigger X Snowboard Bindings, an upgraded version of the Trigger with a Blaster Baseplate for premium shredding comfort and recoil control on harsh landings. The Trigger X has tons of adjustable features and sports a canted footbed for power and edge control with fantastic board feel. Go with your gut and ask questions later on some of the best all-terrain bindings out there.",
    inCart: false,
    count: 0,
    total: 0,
    type: "bindings",
  },
  {
    id: 7,
    brand: "Flow",
    title: "NX2-CX Fusion Snowboard Bindings 2022",
    img: "img/SnowboardBindings/product-2.png",
    price: 220,
    gender: "men's",
    size: ["S , L"],
    info:
      "When you're staring down the barrel of something steep n rocky, you need a set of binders that instills maximum confidence. Enter the Flow NX2-CX Fusion Snowboard Bindings. Built with carbon-infused highbacks and aluminum NX2-Series baseplates, these heavy hitters are ultra-responsive, ultra-precise, and built to take a pummeling and come out the other side begging for more. Flow s Active Strap Technology means less fiddling and less hassle, while new Fusion Exo-Frame PowerStraps offer the latest lightweight tech to keep you nimble on your feet as you billy goat down your line.",
    inCart: false,
    count: 0,
    total: 0,
    type: "bindings",
  },
  {
    id: 8,
    brand: "Flow",
    title: "Micron Snowboard Bindings - Little Kids' 2022",
    img: "img/SnowboardBindings/product-3.png",
    price: 220,
    gender: "kids",
    size: ["S , L"],
    info:
      "If you little ripper is old enough to stand, they're old enough to shred! Get 'em sliding in confidence with the comfortable, easy to use Flow Micron Snowboard Bindings. Flow s rear-entry system allows the highback to fully recline with one easy access lever, perfect for independent minded kids who want to master their own gear quickly.",
    inCart: false,
    count: 0,
    total: 0,
    type: "bindings",
  },
  {
    id: 9,
    brand: "Salomon",
    title: "Quantum Snowboard Bindings 2021",
    img: "img/SnowboardBindings/product-4.png",
    price: 220,
    gender: "men's",
    size: ["S , L"],
    info:
      "The Salomon Quantum Snowboard Bindings are burly freeride bindings with lightweight carbon construction, built for inter-dimensional sends and reality warping speeds. They feature best in class responsiveness for dialed performance and hairpin reactivity, but thanks to Salomon s unique Shadow Fit baseplate system, they still offer a bit of lateral mobility, allowing for a smooth ride that doesn't feel like a lot of the overly rigid, beefed up freeride bindings out there. Strap in and take the leap.",
    inCart: false,
    count: 0,
    total: 0,
    type: "bindings",
  },
  {
    id: 10,
    brand: "Burton",
    title: "Lexa X EST Snowboard Bindings - Women's 2021",
    img: "img/SnowboardBindings/product-5.png",
    price: 220,
    gender: "women's",
    size: ["S , L"],
    info:
      "The Burton Lexa X EST Snowboard Bindings are top level all-mountain binders to get you charging hard on your Burton board. By using Burton s EST system, you get the closest boot to board contact of any binding. When paired with the responsive highback and featherweight construction of the Lexa X, your bindings and feet disappear as you become one with your snowboard, commanding it to rip ever faster down the hill powered by nothing but pure, distilled stoke.",
    inCart: false,
    count: 0,
    total: 0,
    type: "bindings",
  },
  {
    id: 11,
    brand: "DC",
    title: "Control Boa Snowboard Boots 2020",
    img: "img/snowboardsboots/product-1.png",
    price: 220,
    gender: "men's",
    size: ["8 , 9"],
    info:
      "DC Control Boa Snowboard Boots give you dominion over your foot-to-board interface. From their ultra-grippy soles to the pinpoint adjustability of their dual zone Boa closure system, you're always in charge. These boots are made with the rider who does it all in mind: if there's snow, you're on it. These are lightweight, durable, and a proven favorite.",
    inCart: false,
    count: 0,
    total: 0,
    type: "boots",
  },
  {
    id: 12,
    brand: "Burton",
    title: "Moto Boa Snowboard Boots 2020",
    img: "img/snowboardsboots/product-2.png",
    price: 220,
    gender: "men's",
    size: ["8 , 9"],
    info:
      "The Burton Moto Boa Snowboard Boots have been in the Burton lineup for 17 years. With over a decade under its belt, the careful refinement of these legendary boots have made them a must for any novice to experienced shredder who needs the best soft flex boot on the mountain. Stay warm and dry while you carve some surfy lines without any toe drag thanks to the Shrinkage™ footprint reduction technology. Ultimate comfort and an easy-to-use Boa® Coiler™ lacing system make the Burton Moto Boa Snowboard Boots a must for creative riding and park tweaks.",
    inCart: false,
    count: 0,
    total: 0,
    type: "boots",
  },
  {
    id: 13,
    brand: "Salomon",
    title: "Ivy Boa SJ Snowboard Boots - Women's 2021",
    img: "img/snowboardsboots/product-3.png",
    price: 220,
    gender: "women's",
    size: ["7 , 8"],
    info:
      "With a medium fit, a Comfort Liner, and a Boa lacing system, the Salomon Ivy Boa SJ Snowboard Boots appeal to a wide range of riders. The outer Boa keeps your boot shell dialed and has you read to rip with the flick of the wrist, while an interior Str8jkt system locks your heel in place for optimum comfort and performance. Finish it off with a featherweight outsole and a customizable fit, and you've yourself got a performance boot for all occasions.",
    inCart: false,
    count: 0,
    total: 0,
    type: "boots",
  },
  {
    id: 14,
    brand: "Burton",
    title: "Ion Boa Snowboard Boots 2021",
    img: "img/snowboardsboots/product-4.png",
    price: 220,
    gender: "women's",
    size: ["7 , 8"],
    info:
      "With a medium fit, a Comfort Liner, and a Boa lacing system, the Salomon Ivy Boa SJ Snowboard Boots appeal to a wide range of riders. The outer Boa keeps your boot shell dialed and has you read to rip with the flick of the wrist, while an interior Str8jkt system locks your heel in place for optimum comfort and performance. Finish it off with a featherweight outsole and a customizable fit, and you've yourself got a performance boot for all occasions.",
    inCart: false,
    count: 0,
    total: 0,
    type: "boots",
  },
  {
    id: 15,
    brand: "Burton",
    title: "Grom Boa Snowboard Boots - Little Kids' 2021",
    img: "img/snowboardsboots/product-5.png",
    price: 220,
    gender: "kids",
    size: ["7 , 8"],
    info:
      "Grab your grom the perfect pair of starter boots and watch them shoot up the learning curve like a tiny human rocket ship. The Burton Grom Boa Snowboard Boots are simple for your little dude to put on himself, featuring the Boa® closure system for easy, intuitive lacing even with gloves on. A soft, forgiving flex is ideal for messing around in the park and when the next growth spurt hits, remove the Room-To-Grow footbed to squeeze another season out!",
    inCart: false,
    count: 0,
    total: 0,
    type: "boots",
  },
  {
    id: 16,
    brand: "Burton",
    title: "GORE-TEX Vagabond Jacket",
    img: "img/jacket/product-1.png",
    price: 220,
    gender: "kids",
    size: ["S , M , L"],
    info:
      "With full GORE-TEX protection and Burton s Living Lining technology, this is not your average vagabond's trench coat. The Burton GORE-TEX Vagabond Jacket is a long-cut shred shell that gets top marks for both looks and performance. With tons of pockets and a drop hood, this jacket has the retro future flavor you need to let your style loose.",
    inCart: false,
    count: 0,
    total: 0,
    type: "jacket",
  },
  {
    id: 17,
    brand: "Flylow",
    title: "Roswell Insulated Jacket",
    img: "img/jacket/product-2.png",
    price: 220,
    gender: "kids",
    size: ["M , L"],
    info:
      "For a ski jacket that covers all your freeride needs, look no further than the Flylow Roswell Insulated Jacket. With 80 grams of Spaceloft™ synthetic down insulation and Flylow s signature freeride fit, the Roswell has you covered on those bitter cold bluebird mornings. Built from a dependable 2-layer, 10k/10k fabric, the Flylow Roswell Insulated Jacket pairs the look you seek with the weather-proof goods you demand.",
    inCart: false,
    count: 0,
    total: 0,
    type: "jacket",
  },
  {
    id: 18,
    brand: "Quiksilver",
    title: "Tamarack Jacket",
    img: "img/jacket/product-3.png",
    price: 220,
    gender: "kids",
    size: ["M , L"],
    info:
      "Clap back at the snow stacks with the Quiksilver Tamarack Jacket. Quiksilver provides waterproof, breathable DryFly tech that shields you from the elements while WarmFlight Eco insulation keeps you warm enough to slash and slide all day. The Tamarack has plenty of pockets to keep you provisioned through the whole barrage. And, big bonus, the fabric and insulation of this jacket are made of recycled material.",
    inCart: false,
    count: 0,
    total: 0,
    type: "jacket",
  },
  {
    id: 19,
    brand: "Airblaster",
    title: "Trenchover Jacket - Women's",
    img: "img/jacket/product-4.png",
    price: 250,
    gender: "women's",
    size: ["M , L"],
    info:
      "Dripping with style, the Airblaster Trenchover Jacket isn't your traditional antique-looking pullover. This versatile weather shield cuts out the frills for simple storage in your pack that you can deploy once the clouds turn. Fully taped seams and 15K protection mean you can shred in any weather and keep the elements outside where they belong.",
    inCart: false,
    count: 0,
    total: 0,
    type: "jacket",
  },
  {
    id: 20,
    brand: "Obermeyer",
    title: "Nadia Jacket - Women's",
    img: "img/jacket/product-5.png",
    price: 250,
    gender: "women's",
    size: ["M , L"],
    info:
      "Boost your winter style and comfort with the waterproof, breathable, and high-performing Obermeyer Nadia Jacket. This winter coat is made to keep you dry and warm in dynamic conditions without sacrificing on sleek, clean aesthetics. Strategically mapped insulation ups the warmth in the places that matter most while leaving a wide range of motion available. There's ample luxury and tons of refinements here. All these features in the Obermeyer Nadia Jacket are there to improve your wintertime experience for fuller adventures at the resort.",
    inCart: false,
    count: 0,
    total: 0,
    type: "jacket",
  },
  {
    id: 21,
    brand: "Burton",
    title: "GORE-TEX Vent Pants",
    img: "img/pants/product-1.png",
    price: 120,
    gender: "men's",
    size: ["M , L"],
    info:
      "Just because you're a dedicated winter warrior doesn't mean you have to be a sweaty one. Work hard on the bootpack or the skintrack, or just shred to your max capacity on warm spring days, and don't worry about moisture buildup in the Burton GORE-TEX Vent Pants. With the breathbility of Burton s Living Lining, plus Crossflow ventilation in the legs, these pants will give you room to breath when you need it. But batten down the hatches and close up the vents and you've still got the dependability of two layer GORE-TEX for your storm riding needs.",
    inCart: false,
    count: 0,
    total: 0,
    type: "pants",
  },
  {
    id: 22,
    brand: "Volcom",
    title: "3L GORE-TEX Bib Pants",
    img: "img/pants/product-2.png",
    price: 120,
    gender: "me's'",
    size: ["M , L"],
    info:
      "Just because you're a dedicated winter warrior doesn't mean you have to be a sweaty one. Work hard on the bootpack or the skintrack, or just shred to your max capacity on warm spring days, and don't worry about moisture buildup in the Burton GORE-TEX Vent Pants. With the breathbility of Burton s Living Lining, plus Crossflow ventilation in the legs, these pants will give you room to breath when you need it. But batten down the hatches and close up the vents and you've still got the dependability of two layer GORE-TEX for your storm riding needs.",
    inCart: false,
    count: 0,
    total: 0,
    type: "pants",
  },
  {
    id: 23,
    brand: "Volcom",
    title: "Roan Bib Overalls",
    img: "img/pants/product-2.png",
    price: 100,
    gender: "men's",
    size: ["M , L"],
    info:
      "If you've never ridden with bibs then you're in for a great ride when you head out in the Volcom Roan Bib Overalls. Packing a 15k stretch construction and modern relaxed fit for complete uninhibited movement, the ROAN features adjustable suspenders and a jacket to pant interface for deep days.",
    inCart: false,
    count: 0,
    total: 0,
    type: "pants",
  },
  {
    id: 24,
    brand: "VolArmada com",
    title: "Basa Insulated Pants - Women's",
    img: "img/pants/product-4.png",
    price: 120,
    gender: "women's",
    size: ["M , L"],
    info:
      "The Armada Basa Insulated Pants are comfortable, waterproof, and warm, with all the technical features necessary to have a good day out on the hill. If you need a solid, high quality pair of snow pants that get the job done and make you feel great while you shred, give these puppies a try.",
    inCart: false,
    count: 0,
    total: 0,
    type: "pants",
  },
  {
    id: 25,
    brand: "Volcom",
    title: "Swift Bib Overalls - Women's",
    img: "img/pants/product-5.png",
    price: 120,
    gender: "women's",
    size: ["S ,  M , L"],
    info:
      "For deep days and epic conditions, reach for the Volcom Swift Bib Overalls to protect you against pesky snow leakage into your layers. They feature 15K protection and fully taped seams so you can embrace the epic line before you without distraction from old, deteriorating gear. The fit is slim and efficient with a bit of stretch to it for mobility while getting in turns without restriction.",
    inCart: false,
    count: 0,
    total: 0,
    type: "pants",
  },
  {
    id: 26,
    brand: "POC",
    title: "Auric Cut Backcountry SPIN Helmet",
    img: "img/helmet/product-1.png",
    price: 120,
    gender: "men's",
    size: ["S , M , L"],
    info:
      "Smash the park, hit that cliff line under the lift, then venture outside of Jerry's reach for tasty backcountry lines - all in a helmet built to send. The POC Auric Cut Backcountry SPIN Helmet is kitted out to keep you safe and comfortable. The hefty ABS shell uses an EPP liner that better retains it's shape after impacts for longer lasting protection. New for the Cut is POC s SPIN technology that uses specially crafted shearing pads to reduce the effects of an oblique impact. With mad internal padding, on-the-fly adjustable venting, and audio compatibility, the POC Auric Cut Helmet is exactly what is sounds like, it's the cut.",
    inCart: false,
    count: 0,
    total: 0,
    type: "helmet",
  },
  {
    id: 27,
    brand: "Giro",
    title: "Neo Helmet",
    img: "img/helmet/product-2.png",
    price: 120,
    gender: "men's",
    size: ["S , M , L"],
    info:
      "If real is what you can feel, smell, taste, and see, then 'real' is simply electrical signals interpreted by your brain. Shatter your perception of reality this winter and see what new heights you can reach in the Giro Neo Helmet. Thermostat Control and Stack Ventilation keep you fog-free and acclimatized, with Vertical Tuning and an In Form system for a secure, comfortable fit. Control your destiny and ski like the chosen one this winter in the Giro Neo Helmet.",
    inCart: false,
    count: 0,
    total: 0,
    type: "helmet",
  },
  {
    id: 28,
    brand: "Giro",
    title: "Buzz MIPS Helmet - Little Kids'",
    img: "img/helmet/product-3.png",
    price: 120,
    gender: "kids",
    size: ["S , M , L"],
    info:
      "Just when you thought your grom couldn't get any faster, they drop the lens on the Giro Buzz MIPS Helmet and zip off in a cloud of snow. The futuristic style of the Buzz takes a load off your shoulders, making misplaced goggles a thing of the past. And with MIPS technology and the In Form Fit System, all day comfort and protection are guaranteed.",
    inCart: false,
    count: 0,
    total: 0,
    type: "helmet",
  },
  {
    id: 29,
    brand: "Giro",
    title: "Article Goggles",
    img: "img/goggles/product-1.png",
    price: 120,
    gender: "kids",
    size: [],
    info:
      "Brand new gear for those specs of yours. The Giro Article Goggles are loaded to the rafters with good stuff - a semi-framless EXV base with triple layer face foam and helmet compatibility starts things off, while the set of toric, spherical Zeiss lenses cover your bases for absolute clarity in almost any light conditions. Strap on the Giro Article Goggles and rip line after tasty line, whether it's bluebird, greybird or downright blizzarding.",
    inCart: false,
    count: 0,
    total: 0,
    type: "goggles",
  },
  {
    id: 30,
    brand: "Dragon",
    title: "X1s Goggles",
    img: "img/goggles/product-2.png",
    price: 120,
    gender: "kids",
    size: [],
    info:
      "For all your gnarly astronauts, the Dragon X1s Goggles have landed. With the same frameless design as the original APX, but a slightly smaller frame size, the Dragon X1s Goggles are for interstellar explorers without Jupiter-sized domes. These goggles feature Dragon s optically-correct lenses, super anti-fog coating, and the patented easy lens interchange system. Armored venting along the top of the frame is burly but still allows moisture to move freely. Whether you're thinking about sending it into orbit, or just spaced and cruising groomers, the Dragon X1s Goggles come in peace.",
    inCart: false,
    count: 0,
    total: 0,
    type: "goggles",
  },
  {
    id: 31,
    brand: "Marker",
    title: "Squadron Goggles",
    img: "img/goggles/product-3.png",
    price: 120,
    gender: "kids",
    size: [],
    info:
      "Zipping down the hill wearing the Marker Squadron Goggles feels like looking through the windshield of a stealth fighter jet as you prey on the landscape. The MarkAIR vent system keeps your lenses fog-free and the NMT Optics 3rd Eyelid repels dirt and grime for lasting clarity. The Superfit frame design with triple layer face foam fits your face like a glove. Now buckle in and fly!",
    inCart: false,
    count: 0,
    total: 0,
    type: "goggles",
  },
];

export const detailProduct = {
  id: 1,
  brand: "",
  title: "",
  img: "",
  price: 10,
  company: "",
  info: "",
  inCart: false,
  count: 0,
  total: 0,
};
